#!/bin/bash -eu
SCRIPT_DIR=`cd $(dirname "$0"); pwd` # Script can now run from anywhere
. "$SCRIPT_DIR"/timbash/lib/lib-logging.sh       # Set up logging

# local settings
function timconfig_contents {
  cat <<- EOM
  # This file contains local config settings for the timconfig repo
  export TIMCONFIG_HOME=$SCRIPT_DIR
EOM
}
TIMCONFIG_LOCATION=~/.timconfig

if [ -f $TIMCONFIG_LOCATION ] ; then
  if [ "`echo "$(timconfig_contents)" | diff - $TIMCONFIG_LOCATION`" != "" ] ; then
    error "Local config '$TIMCONFIG_LOCATION' is different to autogenerated one"
  fi
else
  log "Creating ~/.timconfig local settings"
  echo "$(timconfig_contents)" > ~/.timconfig 
fi


function inst {
  if [ -f ~/."$1" ] ; then
    DIFF=$(diff ~/."$1" "$SCRIPT_DIR"/master-config/."$1")
    if [ "$DIFF" != "" ] ; then
      error "Skipping $1, because there's a different local version"
    fi
  else 
    log "Installing $1"
    ln -s "$SCRIPT_DIR"/master-config/."$1" ~/."$1"
  fi
}

inst vimrc
inst bashrc
inst profile
inst bash_profile
inst gitignore_global

log "Configuring git to always use ssh and use gitignore_global" 
git config --global url."git@github.com:".insteadOf "https://github.com/" # This allows private repos in Go, among other things
git config --global core.excludesfile ~/.gitignore_global
