#!/bin/bash -eu
SCRIPT_DIR=`cd $(dirname "$0"); pwd` # Script can now run from anywhere
. "$SCRIPT_DIR"/timbash/lib/lib-logging.sh       # Set up logging

trap 'error "Installation failed"' 0

# local settings
function timconfig_contents {
  cat <<- EOM
  # This file contains local config settings for the timconfig repo
  export TIMCONFIG_HOME=$SCRIPT_DIR
EOM
}
TIMCONFIG_LOCATION=~/.timconfig

if [ -f $TIMCONFIG_LOCATION ] ; then
  if [ "`echo "$(timconfig_contents)" | diff - $TIMCONFIG_LOCATION | cat`" != "" ] ; then
    warn "Local config '$TIMCONFIG_LOCATION' is different to autogenerated one"
  fi
else
  log "Creating ~/.timconfig local settings"
  echo "$(timconfig_contents)" > ~/.timconfig 
fi

log "Installing..."

function inst {
  if [ -f ~/"$1" ] ; then
    DIFF=$(diff ~/"$1" "$SCRIPT_DIR"/master-config/"$1" | cat)
    if [ "$DIFF" != "" ] ; then
      warn "Skipping ~/$1,  because there's a different local version"
    else 
      warn "Already installed: $1"
    fi
  else 
    log "Installing $1"
    ln -s "$SCRIPT_DIR"/master-config/"$1" ~/"$1"
  fi
}

for f in .vimrc .bashrc .profile .bash_profile .gitignore_global; do
  inst $f
done
  
log "Configuring git to always use ssh and use gitignore_global" 
git config --global url."git@github.com:".insteadOf "https://github.com/" # This allows private repos in Go, among other things
git config --global core.excludesfile ~/.gitignore_global

trap 'log "Install success"' 0
